pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                echo 'Simulating test execution...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Simulating deployment step...'
            }
        }
    }
}
