pipeline {
    agent any
    tools {
        maven 'Maven-3.9.9'
    }
    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
        stage('Build with Maven') {
            steps {
                // Change to the ci-demo directory before running Maven
                dir('ci-demo') {
                    sh 'mvn clean install'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Running Tests...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}
